name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-staging:
    name: Deploy to Staging
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Staging Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: src
          skip_app_build: true

  close-staging:
    name: Close Staging Environment
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Close Staging Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: close

  deploy-production:
    name: Deploy to Production
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: src
          skip_app_build: true